### ISSUE TITLE
total lack of useful context in error messages

### ISSUE THREAD

**Issue by oryband** [buildinspace/peru#128]
using the following `peru.yaml`:

``` yaml
imports:
  repo: dir/

git module repo:
  url: git@github.com:me/repo.git
  pick: inner_dir/**
```

and then invoking `peru sync` results in:

```
The "files" field is no longer supported. Use "pick" instead.
```

as you can see i'm not using `fields` at all. this also happens if I remove the `pick:` line.

any idea?
