### ISSUE TITLE
Versions and constraints?

### ISSUE THREAD

**Issue by Hologos** [buildinspace/peru#193]
Hi,

I just found peru and have played with that a little. I would really love to deploy this to our company but I am missing one key feature. We need the ability to lock modules to a specific version (tag preferably) or better, to be able to specify a constrain for version.

**Example** 
```yaml
imports:
    rack_example: rack/  # This is where we want peru to put the module.

git module rack_example:
    url: git://github.com/chneukirchen/rack.git
    version: 1.3
```

This would fetch only module with version 1.3.*. We need this because our imaginary project is compatible with rack 1.3, not with 1.4 but we still want patches for 1.3. If I `peru reup`, it downloads the most recent version, which is 1.4.1.

I know I can write my own plugin (and I probably will for tarballs), but I would really like to use builtin plugins so I wouldn't have to deploy all plugins to all new employees that join our company.

The best option would be to implement something like [composer has](https://getcomposer.org/doc/articles/versions.md) (and other dependency managers).

**Comment by oconnor663** [comment]
If the versions are available as git branches or tags, peru already supports fetching them. For example, this is valid:

```yaml
git module rack:
    url: https://github.com/chneukirchen/rack
    rev: 1.4.1
```

In general, whatever you put in `rev` gets passed to the `git rev-parse` command under the covers. One thing to note is that, by default, `peru reup` will still replace that `rev` field with the master commit hash. You can run `peru reup [some other module]` to avoid this, or you can also do something like the following to tell reup to target something other than master for this module:

```yaml
git module rack:
    url: https://github.com/chneukirchen/rack
    reup: 1.4.1
    rev: c78d30ae39b437420cc94b62002ccc1ac0337cc7
```

Since you mentioned tarballs, did you catch the `unpack: tar` example in the readme. It's might be that peru already supports what you need there also, via the `curl` plugin. (Which is not in fact implemented with command line `curl`, but rather Python's standard HTTP libraries.)
