### ISSUE TITLE
Support for providing username and password for curl downloads

### ISSUE THREAD

**Issue by colindean** [buildinspace/peru#195]
I'd like to retrieve dependencies from a private URL that requires credentials. In my current setup, I'm using `curl --netrc`, which enables me to put a hostname, username, and password into `~/.netrc`. 

Poking through the source of the curl module, I see https://github.com/buildinspace/peru/blob/42ad4ad5eabbe6e6872d2b6f4c459475e4051304/peru/resources/plugins/curl/curl_plugin.py#L82 is where the request is created. I looked at the [urllib.request docs](https://docs.python.org/3.7/library/urllib.request.html) and see this example for setting up for basic auth:

```python
import urllib.request
# Create an OpenerDirector with support for Basic HTTP Authentication...
auth_handler = urllib.request.HTTPBasicAuthHandler()
auth_handler.add_password(realm='PDQ Application',
                          uri='https://mahler:8092/site-updates.py',
                          user='klem',
                          passwd='kadidd!ehopper')
opener = urllib.request.build_opener(auth_handler)
# ...and install it globally so it can be used with urlopen.
urllib.request.install_opener(opener)
urllib.request.urlopen('http://www.example.com/login.html')
```

netrc parsing is, fortunately, a standard library feature of Python, through the aptly-named [`netrc` library](https://docs.python.org/3.7/library/netrc.html).

The implementation of this all seems pretty straightforward but the _configuration_ within peru is unclear. It would probably make sense for peru to read this file and populate the opener by default but I could see how some users may feel that's a security risk. So, a compromise may be opt-in in the peru.yml, an `auth` block:

```yaml
# from the example in README.md
curl module pathogen:
    url: https://codeload.github.com/tpope/vim-pathogen/tar.gz/v2.3
    auth: netrc
    # Untar the archive after fetching.
    unpack: tar
    # After the unpack, use this subdirectory as the root of the module.
    export: vim-pathogen-2.3/autoload/

curl module pathogen:
    url: https://codeload.github.com/tpope/vim-pathogen/tar.gz/v2.3
    auth:
        username: whatever
        password: whywouldyouputthathere
    # Untar the archive after fetching.
    unpack: tar
    # After the unpack, use this subdirectory as the root of the module.
    export: vim-pathogen-2.3/autoload/
```

**Comment by oconnor663** [comment]
Interesting idea. How do you think we'd handle a project that has two or more modules requiring authentication, but their credentials are different. I'm not familiar with the netrc format, so I don't know if there's an obvious convention for this.

**Comment by colindean** [comment]
netrc format is this:

```netrc
machine 1.example.com login myusername password @#$%!
machine 2.example.com
  login myusername
  password @#$%!
default
login myusername
password @#$%!
```

All lines are valid, where `machine` is an identifier of some kind, generally a hostname or IP address. I'm not sure how netrc recommends handling two sets of credentials for the _same_ machine other than to try them sequentially. There is a keyword `default` that can replace `machine` and indicates that it's the last thing to be tried with _any_ hostname matching should previous definitions fail.

More info on curl's usage here: https://ec.haxx.se/usingcurl-netrc.html

**Comment by oconnor663** [comment]
I think if the netrc file indicates that foo.com should have a username and password, then it's probably ok for any `curl` module pointed at foo.com to use it. An extra field like `auth: true` wouldn't really change much, I think. If the idea is that the `peru.yaml` file isn't trusted, well, the untrusted author could just insert the `auth` flag too.

Would you be willing to put together a PR for this? I'd be happy to review it. I'm not sure how to test it though -- can Python's HTTPServer be set up locally to require this type of auth? Is there a standard environment variable we might want to use to override the `~/.netrc` path for testing / in general?

**Comment by colindean** [comment]
I'll see what I can drum up!

**Comment by Hologos** [comment]
> If the idea is that the peru.yaml file isn't trusted, well, the untrusted author could just insert the auth flag too.

From my point of view, it's not about `peru.yaml` isn't trusted. It think it's not good idea in general to store credentials in a repository. And since `peru.yaml` **should** be stored in a repository, it **should not** contain fields `username` and `password`.

I really like the idea of `.netrc` file, though.

**Comment by felipefoz** [comment]
Hi,
Is anyone up for PR review of this feature?

I am in need of this feature in a near feature, so I might start working on it if you are willing to accept.

**Comment by oconnor663** [comment]
Yes I'm happy to review. (Though please ping me if I miss an email and it seems like I'm not responding.) Here are the two main design issues as I understand them:

- Since we're talking about passwords, the best method for obtaining them (e.g. in modern CI testing environments like GitHub Actions) is from the environment. Hardcoding them in `peru.yaml` is of course a potential footgun, and outsourcing them to another file is probably the same footgun. There _might_ be some use cases where putting passwords in files is acceptable (legacy systems with public but nonempty passwords?), but I'd want to be real sure there's a good use case before even supporting such a feature.
- Because different modules might need different passwords, we could consider letting the module specify the name of the variable that should be read to provide its password. Alternatively, maybe we could look automatically look for an environment variable like `PERU_CURL_PASSWORD_*` where `*` is the uppercased module name. A similar approach is [already in use internally](https://github.com/buildinspace/peru/blob/master/docs/architecture.md#plugins). That has the advantage of not requiring any changes to `peru.yaml`, maybe at the cost of some flexibility? (Does any use case really need that flexibility?)

Let me know your thoughts.

**Comment by felipefoz** [comment]
Yes, I declined the netrc approach when I started considering a CI idea, it would not be so feasible.

This environment variable approach would be probably the safest option and the quickest.

Just not to discard, I also did some investigation on some other options, and the git config url.insteaof sounds interesting. Because it could be used implicitly by the git plugin too.

But for the curl plugin, it would require parsing the git config file and loading internally. There is a git config library for python, but I am not so sure it is needed for this use case.

**Comment by felipefoz** [comment]
Hi, 

I've been thinking about this feature, and I've had two approaches:

1. Use environment variables to get password. But, in this case, we also might need a user name. So, every module would need a user and a password environment variable, in my opinion, this does not scale very well. One or two modules, ok, but downloading from the same source could be more efficient. 
Good Point: we know it has a good chance of working. 
Bad point: it does not scale well.

2. Second option is using git config options. In this case, you could use the command.
`git config url."https://user@password:somewebsite.com".insteadOf https://somewebsite.com`
Some tests I did (gitlab), if you put the user and password as secrets, it does not persist across jobs (sessions).
Second thing, it can be used implicitly by the git module.
For using in the curl module, we would have to parse the base url to extract only the "root" and check against this configuration using ConfigParser. 
Good point: it works for git module, and for multiple modules from same source. 
Bad Point: I have not tested yet, we can have surprises.

What do you think?

**Comment by colindean** [comment]
It's great to see traffic on this issue! I've long since moved on from the org that inspired my original submission but recently returned to using Peru _and_ simultaneously working in Python for the first time in 15 years... but I have very little spare time nowadays.

I'd say that designing this well could enable _all_ of these credential resolution methods. I'd recommend choosing environment variables as the first implementation. Doing something as @oconnor663 suggests with a module name in the envvar should be a first pass expanding perhaps the domain of the target system, but these both are limited in applicability mostly to `curl`, I think. Envvars are _far_ more likely to be used in CI systems and if a user finds the number of envvars to be burdensome, they're going to script something to set the envvars anyway.

The VCS modules (git, hg, svn) should be configured the way their systems expect it. As such, I discourage putting credentials into `.git/config`. Instead, the user should configure their git repo with [a credentials helper](https://git-scm.com/docs/gitcredentials). Following this logic, because cURL provides a mechanism for credential retrieval from a file in the form of netrc support, Peru should support that convention. However, Peru's "curl" plugin doesn't _actually_ use cURL: it just uses Python's `urllib.request`. I kinda wish a future version of Peru would disambiguate, renaming its internal HTTP retrieval something like "http" and enabling the curl plugin to use literally cURL.

https://github.com/buildinspace/peru/blob/e9ba6e0024ea08105a8d027f958899cca39aeb9a/peru/resources/plugins/curl/curl_plugin.py#L12

So, if Peru were to support envvars at a basic level enough to satisfy one scale level (maybe up to 10 modules requiring authentication; little effort put into deduplication: exercise left to implementor) and then choose the standard netrc format for the next scale level (beyond 10 modules) for the "curl" plugin, I think it would have a solid and secure interface for that plugin. The other modules' credentials are set however their respective system specify and that's something left to the Peru user to configure safely using those systems (mostly VCS) credential storage.

To properly support password auth for rsync, Peru would have to set `RSYNC_PASSWORD` or pass `--password-file`. N.b. this is only for accessing a secured rsync _server_, not rsync over SSH, which uses SSH credential storage.

**Comment by felipefoz** [comment]
> The VCS modules (git, hg, svn) should be configured the way their systems expect it. As such, I discourage putting credentials into .git/config. Instead, the user should configure their git repo with a credentials helper.

Perfect, that's correct.

> I kinda wish a future version of Peru would disambiguate, renaming its internal HTTP retrieval something like "http" and enabling the curl plugin to use literally cURL.

I totally agree. Maybe we could come up with an alias to not break compatibility.

> So, if Peru were to support envvars at a basic level enough to satisfy one scale level (maybe up to 10 modules requiring authentication; little effort put into deduplication: exercise left to implementor) and then choose the standard netrc format for the next scale level (beyond 10 modules) for the "curl" plugin, I think it would have a solid and secure interface for that plugin.

I totally disagree. I think we should come up with a solution for all cases. No one wants to spend extra time doing this "deduplication". If it is someone new coming to the tool, this person wants a solid tool. We don't want to scare people from here, do we?

> The netrc implementation should read the file and pass the credentials into a HTTPPasswordMgr instance used by urllib. The other modules' credentials are set however their respective system specify and that's something left to the Peru user to configure safely using those systems (mostly VCS) credential storage.

How we would write to this file? Where are you storing this file?

**Comment by colindean** [comment]
> > I kinda wish a future version of Peru would disambiguate, renaming its internal HTTP retrieval something like "http" and enabling the curl plugin to use literally cURL.
> 
> I totally agree. Maybe we could come up with an alias to not break compatibility.

I could see this rolling out in a major release. In a minor release (e.g. 1.5.0), introduce the `http` as an alias for `curl` and emit a warning that `curl` will be renamed `http` in a future release. When the major release comes out (say, 2.0.0), the `curl` plugin should still maintain _configuration_ compatibility even though the underlying mechanism is different. Only upon  the next major release (3.0.0) should any backward-incompatible changes occur in order to maintain _strict_ semver. I tend to abide by strict semver myself but have seen some software with other major, highly-desirable improvements delay breaking changes to the first minor release with adequate notification in the major release and warnings in the logs, etc.

> > So, if Peru were to support envvars at a basic level enough to satisfy one scale level (maybe up to 10 modules requiring authentication; little effort put into deduplication: exercise left to implementor) and then choose the standard netrc format for the next scale level (beyond 10 modules) for the "curl" plugin, I think it would have a solid and secure interface for that plugin.
> 
> I totally disagree. I think we should come up with a solution for all cases. No one wants to spend extra time doing this "deduplication". If it is someone new coming to the tool, this person wants a solid tool. We don't want to scare people from here, do we?

To clarify, by _deduplication_, I mean enabling two modules that share credentials to reference the same credential set. For example, for two modules with the names `foo` and `bar`:

```shell
PERU_PLUGIN_HTTP_CRED_FOO_USERNAME="asdf"
PERU_PLUGIN_HTTP_CRED_FOO_PASSWORD="hunter2"
PERU_PLUGIN_HTTP_CRED_BAR_USERNAME="asdf"
PERU_PLUGIN_HTTP_CRED_BAR_PASSWORD="hunter2"
```

This will quickly grow unwieldy, obviously, but enabling envvars in this way lends itself to this following configuration in nearly all CI configurations, I speculate:

```yaml
# vela/drone object style
environment:
  MYSERVICE_USER: "asdf"
  MYSERVER_PASS: "hunter2"
  PERU_PLUGIN_HTTP_CRED_FOO_USERNAME: "${MYSERVICE_USER}"
  PERU_PLUGIN_HTTP_CRED_FOO_PASSWORD: "${MYSERVER_PASS}"
  PERU_PLUGIN_HTTP_CRED_BAR_USERNAME: "${MYSERVICE_USER}"
  PERU_PLUGIN_HTTP_CRED_BAR_PASSWORD: "${MYSERVER_PASS}"
```

Eventually, this is going to have to be defined _somehow_, even if it ends up being a step in CI to avoid the introduction of a ton of envvars:

```yaml
curl module mypackage:
    url: https://myservice.example.com/packages/mypackage-1.2.4.tar.gz
    # this module _could_ automatically look at .netrc if it exists...
    auth: netrc
    # Untar the archive after fetching.
    unpack: tar
    # After the unpack, use this subdirectory as the root of the module.
    export: mypackage
```

```yaml
# using Vela- and Drone-like config because I know it well enough to not look at docs ;-)
steps:
  - name: write .netrc
    image: alpine:latest
    commands:
    - echo "machine myservice.example.com login ${MYSERVICE_USER} password ${MYSERVICE_USER}" > .netrc
    - chmod 400 .netrc
  - name: get modules using netrc
    image: buildinspace/peru:latest
    commands:
    - peru sync
    # or specified instead of discovered in ./.netrc, ~/netrc, /etc/netrc, etc. whatever Python's netrc resolver does is fine
    - peru sync --netrc .netrc
  - name: get modules using envvars
    image: buildinspace/peru:latest
    environment:
      - PERU_PLUGIN_HTTP_CRED_MYPACKAGE_USERNAME: ${MYSERVICE_USER}
      - PERU_PLUGIN_HTTP_CRED_MYPACKAGE_PASSWORD: ${MYSERVICE_PASS}
    commands:
    - peru sync
    # or specified instead of discovered in ./.netrc, ~/netrc, /etc/netrc, etc. whatever Python's netrc resolver does is fine
    - peru sync --netrc .netrc
secrets:
- type: native
  name: myservice_user
  target: MYSERVICE_USER
- type: native
  name: myservice_pass
  target: MYSERVICE_PASS
```



> 
> > The netrc implementation should read the file and pass the credentials into a HTTPPasswordMgr instance used by urllib. The other modules' credentials are set however their respective system specify and that's something left to the Peru user to configure safely using those systems (mostly VCS) credential storage.
> 
> How we would write to this file? Where are you storing this file?

Peru would not create it. Such _feels_ like it could inevitably necessitate Peru allowing the definition of credentials in its configuration. That repeats a common security footgun pattern out of convenience!

Most likely, a user would create it at repo setup time, including CI preparation steps. Some CI systems, notably Travis, enable users to store entire files in secret storage and that file is written to a predictable location on the runner or in the working directory before all CI steps. Vela and Drone write declared secrets as a file to a `/vela/secrets` hierarchy, IIRC, and limit secret content to like 5 KiB, "which ought to be enough for anybody".

At a previous job, I accessed a number of services behind authentication and carried a `.netrc` file in my home directory for a few years alongside my SSH keys, etc.
