### ISSUE TITLE
feature_request(enhancement): rename downloaded folders

### ISSUE THREAD

**Issue by Kristinita** [buildinspace/peru#205]
### 1. Summary

It would be nice, if peru can rename downloaded folders without using third-party tools.

#### 2.1. git

[**Change name of folder when cloning from GitHub**](https://stackoverflow.com/a/8570660/5951529):

```text
git clone https://github.com/kira/pelican-kiragoddess.git kiragoddess
```

Repository clone to `kiragoddess`, not `pelican-kiragoddess` folder.

#### 2.2. Python

[**Aliasing modules**](https://www.digitalocean.com/community/tutorials/how-to-import-modules-in-python-3#aliasing-modules):

```python
import pelican_kiragoddess as kiragoddess
```

### 3. Argumentation

I use [**plugins for Pelican**](https://github.com/getpelican/pelican-plugins) — static sites generator. Names of some plugins begin to `pelican-` or `pelican_`:

![pelican- plugins](https://i.imgur.com/lUcDMr3.png)

That use some plugins, user needs to remove `pelican-` or `pelican_` from plugin folder name. For example, if folder name is `open_graph`, Pelican will works; else `pelican-open_graph` — no.

### 4. Example of expected behavior

For `peru.yaml`:

```yaml
imports:
  pelican-plugins: plugins/

git module pelican-plugins:
  url: https://github.com/getpelican/pelican-plugins
  pick:
  - pelican-open_graph
  - sitemap
```

New `peru.yaml`:

```yaml
imports:
  pelican-plugins: plugins/

git module pelican-plugins:
  url: https://github.com/getpelican/pelican-plugins
  pick:
  - pelican-open_graph
  - sitemap

renames:
  pelican-open_graph: open_graph
```

Folder `pelican-open_graph` will rename to `open_graph`.

Thanks.

**Comment by oconnor663** [comment]
Again apologies for leaving you hanging for so long. You put a lot of effort into these issues, and I feel bad for not responding promptly.

I think what you're trying to do works today with the `move` field. Try this:

```yaml
imports:
  pelican-plugins: plugins/

git module pelican-plugins:
  url: https://github.com/getpelican/pelican-plugins
  move:
    pelican-open_graph: open_graph
  pick:
    - open_graph
    - sitemap
```
