### ISSUE TITLE
feature_request(dry): get variables from another YAML files

### ISSUE THREAD

**Issue by Kristinita** [buildinspace/peru#206]
**#199** — partially related issue

### 1. Summary

It would be nice, if peru can get variables from another YAML files.

### 2. Argumentation

[**Don't Repeat Yourself**](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch30.html).

At the time I need to write duplicate code for using Peru.

#### 3.1. Structure and files

Part of my real project structure:

```text
peru.yaml
site_variables.yaml
pelican-config/
  pelican_plugins_settings.yaml
```

+ `peru.yaml`:

```yaml
imports:
  pelican-plugins: plugins/

git module pelican-plugins:
  url: https://github.com/getpelican/pelican-plugins
  pick:
  - filetime_from_git
  - interlinks
  - just_table
  - neighbors
  - pelican-open_graph
  - section_number
  - sitemap
```

+ part of `site_variables.yaml`:

```yaml
PLUGIN_PATHS:
- plugins
```

+ part of `pelican-config/pelican_plugins_settings.yaml`:

```yaml
PLUGINS:
- filetime_from_git
- interlinks
- just_table
- neighbors
- pelican-open_graph
- section_number
- sitemap
```

#### 3.2. Problem

I use duplicate values for:

1. `pick` variable in peru and `PLUGINS` variable for Pelican.
1. `imports.pelican-plugins` — peru; `PLUGIN_PATHS` — Pelican.

If I change Pelican variable, I need manually make the same change for peru. I need to repeat myself.

### 4. Not helped

1. Unfortunately, [**YAML doesn't support any kind of `include` or `import` statement**](https://stackoverflow.com/a/15437697/5951529). I can't find, how I can solve my problem use third-party tools.
1. Pelican required, for example, `PLUGINS` variable name. I can't change it to `git module pelican-plugins.pick` for using peru with [**`--file-basename` flag**](https://github.com/buildinspace/peru#configuration).

### 5. Example of expected behavior

+ `peru.yaml`:

```yaml
include: site_variables.yaml
include: pelican-config/pelican_plugins_settings.yaml

imports:
  pelican-plugins: site-variables.PLUGIN_PATHS

git module pelican-plugins:
  url: https://github.com/getpelican/pelican-plugins
  pick: pelican_plugins_settings.PLUGINS
```

Thanks.
