### ISSUE TITLE
Feature Request: Add to .gitignore

### ISSUE THREAD

**Issue by chenboshuo** [buildinspace/peru#228]
I think  we run 
```bash
peru reup 
```
we can search the `.gitignore` mark
```text
# peru files
```

 and add items to them.

For instance,
if I have the `peru.yaml` file like:

```yaml 
imports:
  my_silde: notes/

git module my_silde:
  url: git@github.com:chenboshuo/myslide_template.git
  pick: [makefile,myslide.cls]
  rev: cf178c930b5702230fb2dc953873aa202d404aa6
```
And we setting the setting items in `peru.yaml`:
```yaml
settings:
  auto-ignore: true
```

and I have `.gitignore` like:
```text
# peru
**/.peru

# peru files
```
after my run `peru reup`,
the  `.gitignore` become:
```diff
# peru
**/.peru

# peru files
+++ notes/makefile
+++ notes/myslide.cls
```
Thank you for your attention.
