### ISSUE TITLE
on `reup` update rev with latest tag if rev is a tag

### ISSUE THREAD

**Issue by Araxeus** [buildinspace/peru#233]
```yml
imports:
    vscode: scripts/

git module vscode
    url: git://github.com/microsoft/vscode.git
    rev: 1.75.0
```

⏬

```bash
peru reup -f
```

⏬

```yml
imports:
    vscode: scripts/

git module vscode
    url: git://github.com/microsoft/vscode.git
    rev: 1.75.1
```

Currently, the rev will be replaced with the latest commit hash instead of the latest tag
related to https://github.com/buildinspace/peru/issues/193#issuecomment-1433013723
