### ISSUE TITLE
Exclude module from reup

### ISSUE THREAD

**Issue by timdp** [buildinspace/peru#77]
Let's say I want to lock one of my Git modules at a specific tag (e.g., to get a tagged version on the master branch). If I put that tag in `peru.yaml`, running `sync` will pull in revision that I want.

However, I obviously have multiple modules in `peru.yaml`. If I want to update all of them except the one mentioned above, it seems like the only way is to pass all their names to `reup`.

Consequently, I think there should be a way to lock a module to a revision and exclude it from `reup`. It could be an extra rule or some syntactic sugar such as a plus sign in front of the revision ID.

I'm guessing peru will someday gain support for tools that use Semantic Versioning, so the revision/version syntax could presumably use that too.

**Comment by oconnor663** [comment]
It's a total hack, but currently you can do something like this:

```yaml
git module vim-fugitive:
  url: https://github.com/tpope/vim-fugitive.git
  rev:  0374322ba5d85ae44dd9dc44ef31ca015a59097e
  reup: 0374322ba5d85ae44dd9dc44ef31ca015a59097e
```

`peru reup` will still try to update this module, but the update will be a no-op. This isn't necessarily better, but you can do the same without duplication using YAML references:

```yaml
git module vim-fugitive:
  url: https://github.com/tpope/vim-fugitive.git
  rev: &fugitive 0374322ba5d85ae44dd9dc44ef31ca015a59097e
  reup: *fugitive
```

If this is a common use case, I could see adding a global module field like `do not reup: true` or something.\* We probably wouldn't want to do it as extra syntax in the `reup` field -- it turns out that field is implemented by each plugin that supports reup, rather than by peru itself, so any work to parse it would need to be duplicated across plugins. Note also, we've been talking about renaming the `reup` field to something more descriptive, see #74.

\* All the fields that exist right now are strings, so if we did this we'd want to figure out some reasonable convention for booleans -- including how they would get passed through [the plugin interface](https://github.com/buildinspace/peru/blob/master/docs/architecture.md#plugins).
